# Site settings
name: SpaceDog
title: SpaceDog | Smart backend for mobile and web applications
email: hello@spacedog.io
description: > # SpaceDog is the perfect cloud backend for mobile and web applications.
 Forget about server-side pain. Focus on creating amazing user experiences. Sign up and immediately
 access our backend services. Save and search for data. Edit and push new contents. Deploy and publish
 resources and services.

# the subpath of your site, e.g. /blog/
baseurl: ""
# the base hostname & protocol for your site
url: "https://spacedog.io"
github_username:  davattias

# Build settings
markdown: redcarpet
highlighter: pygments

kramdown:
  input: GFM

redcarpet:
  extensions: [tables]

collections:
  user-guide:
    output: true
    permalink: /docs/user-guide/:path:output_ext
  reference-guide:
    output: true
    permalink: /docs/reference-guide/:path:output_ext